### ISSUE TITLE
CamelCase property names

### ISSUE THREAD

**Issue by x2bool** [x2bool/tdsharp#1]
https://github.com/tdlib/td/issues/27#issuecomment-372588668

**Comment by x2bool** [comment]
@karb0f0s There was an attempt to generate all names in CamelCase, but there is a problem with this approach.

Example:

```
messages total_count:int32 messages:vector<message> = Messages;
```

Would be translated to:

```
class Messages
{
   Message[] Messages { get; set; } // produces compile time error
}
```

If we could come up with how to avoid this problem, thne I will be positive on changing property names to CamelCase.

**Comment by karb0f0s** [comment]
As a suggestion - prefix class names with TD, TDMessages for example

**Comment by x2bool** [comment]
Fixed with https://github.com/x2bool/tdsharp/commit/584746c66aaa533b29a96ebbf9d8c06f353fc274
