### ISSUE TITLE
getChats result list not found

### ISSUE THREAD

**Issue by salarvand** [x2bool/tdsharp#2]
hi, thanks for this binding . 
when call request like getChats result list not found but in log file exist ! and result is ok 

  ```
  data = JsonConvert.SerializeObject(new Methods.getChats()
            {
                limit_ = 100,
                offset_chat_id_ = 0,
                offset_order_ = long.MaxValue.ToString()
            });
 Client.Send(data);
 while (true)
  {
      string result = Client.Receive(5);
  }
```
how can retrive result getChats in same thread ?

**Comment by x2bool** [comment]
Hi. In your example client.receive is not guaranteed to return the answer to getChats, could be anything. Use Dialer to send this request (take a look at README.md for example).

**Comment by salarvand** [comment]
i used that before! but not work correctly (in windows) when call  `await dialer.ExecuteAsync`  the hub received handler never called !

```
 private void HubOnReceived(object sender, Structure structure)
  {
            // do somethin
  }

 private static readonly Hub _hub = new Hub(Client);
 private Dialer _dialer = new Dialer(Client, _hub);
 hub.Received +=  HubOnReceived;

var chatsList = await dialer.ExecuteAsync(new Methods.getChats()
          {
              limit_ = 100,
              offset_chat_id_ = 0,
              offset_order_ = long.MaxValue.ToString()
          });
```

**Comment by x2bool** [comment]
Did you call setTdlibParameters, checkDatabaseEncryptionKey and setAuthenticationPhoneNumber and checkAuthenticationCode before executing this?

I use GetChats myself and it works 100%

**Comment by salarvand** [comment]
yes i did and every thing work correctly but my problem is i could not retrieve chats that way !

**Comment by x2bool** [comment]
Just tried this. And it works.

```
var chats = await _dialer.ExecuteAsync(new TD.GetChats
{
    OffsetChatId = 0,
    OffsetOrder = long.MaxValue.ToString(),
    Limit = 50,
});  
```

Please attach your logs and I will try to figure out what's going on.

**Comment by x2bool** [comment]
By the way, I will publish an updated version of the lib in an hour. Try it instead.
