### ISSUE TITLE
Pls provide nuget version

### ISSUE THREAD

**Issue by ahvahsky2008** [x2bool/tdsharp#3]
THX

**Comment by x2bool** [comment]
Fixed in d3a5c05176e472036a0e851f6925f932f272b55b

**Comment by karb0f0s** [comment]
hi, who is responsible for publishing nugets? TDLib is now v1.2 though published v1.0

**Comment by x2bool** [comment]
Hi! I will publish v1.2 today after generating new contracts: https://github.com/x2bool/tdsharp/issues/4
