### ISSUE TITLE
Calling Convention when compiling for Windows

### ISSUE THREAD

**Issue by Rucadi** [x2bool/tdsharp#5]
I couldn't use the NuGet package because of the DLL resulting from compiling td was generating calls with a different convention.

I had to add:

[DllImport("tdjson.dll", CallingConvention = CallingConvention.Cdecl)]

to WindowsBindings for being able to use it.

**Comment by x2bool** [comment]
Do you have any links on why Cdecl has to be used on Windows? In my case it works as intended without setting CallingConvention explicitly on all platforms including Windows.

**Comment by karb0f0s** [comment]
@Rucadi have you followed this instructions [building-tdlib](https://github.com/tdlib/td/tree/master/example/csharp#building-tdlib)?
```
cmake -DTD_ENABLE_DOTNET=ON -DCMAKE_TOOLCHAIN_FILE=C:\src\vcpkg\scripts\buildsystems\vcpkg.cmake ../../..
```
especially this part **cmake -DTD_ENABLE_DOTNET=ON**

**Comment by Rucadi** [comment]
Ok, -DTD_ENABLE_DOTNET=ON was not set so It's my fault for not looking at examples.

It would be nice to support both versions, but I think that is nor relevant nor neccesary.

Well at least I'm positive and thing this issue could help people that faces the same problem in a future.

Thanks for finding the problem that quick!
